### ISSUE TITLE
Model running on CPU and GPU

### ISSUE THREAD

**Issue by TS9001** [VoltaML/voltaML#10]
Hi everyone,

I am trying to optimize distilbert-multilingual-uncased from hugging-face. As suggested in examples I have tried to use VoltaNLPCompile, adding   quantisation parameter, converting only to onnx. During testing model on CPU, everything works like marvel, there is speed up around 3.4times with data processing included. Unfortunately my use-case is quite specific. Distilbert serves as "embedding generator", used during training, which is running on GPU (later on production it is running on CPU for faster inference).
On GPU the model runs aprox. 30x slower than distilbert transformed by onnx. This is a blocker, because embedding vectors generated by this model must be the same, otherwise the performance decrease is quite substantial.

My first guess is that this is caused by some optimalization for CPU, but I don't know enough about this matter.. 
My question is: it a feature, bug or something fixable during model compilation?

Thank you in advance,
Best Regards,
Tom

**Comment by VoltaML** [comment]
Hi Tomas. Did you convert the model into tensorrt format for GPU?

**Comment by TS9001** [comment]
No,  it will ultimately run on the CPU. I need a model to somehow run on GPU (to create embeddings) and use the same, hopefully, more optimal model on CPU.

In the meantime, I was able to reproduce the same behavior with ONXX itself, I think that it is related to this issue https://github.com/microsoft/onnxruntime/issues/10267

I guess that it is not possible right now, am I correct?

**Comment by TS9001** [comment]
I was able to fix issue by different means
