### ISSUE TITLE
Is this project dead? Suggestion about using existing models

### ISSUE THREAD

**Issue by VictorZakharov** [VoltaML/voltaML#11]
Last update to code was in November. Is this project dead?
Many new & cool models came out since then.
Clarity, Deliberate and others.

Also downloading models from the internet is not most efficient, I only get download speeds of 15 MB/s, on a gigabit internet connection. And considering I already have all the models I need, it's really only wasting time. Should be able to mount a docker volume with models that I already have.

**Comment by VoltaML** [comment]
Hey. We are developing actively only on stable diffusion for now, so you can please go to this repo https://github.com/VoltaML/voltaML-fast-stable-diffusion/tree/experimental

**Comment by VictorZakharov** [comment]
@VoltaML So mark this project as archived / read-only and update this readme with a link to new?
- https://github.com/VoltaML/voltaML
