### ISSUE TITLE
This repo is impossible to install locally for developing purposes

### ISSUE THREAD

**Issue by hdnh2006** [VoltaML/voltaML#5]
I have tried almost everything and I have follow the few instructions you provide.

I think the list of requirements should be something like this:

```
numpy
scipy
pillow
torch==1.12.0 # This is a requirement from you
torchvision==0.13.0
decorator 
attrs
tornado
psutil
#xgboost # Just in case you want to optimize a xgboost model
cloudpickle
onnx
onnxoptimizer
tqdm
#time # There's no a package called like this


# Other packages
nvidia-pyindex  # TensorRT index
nvidia-tensorrt<8.5 # I couldn't install the tensorrt version your repo require
PyYAML
pandas
opencv-python
matplotlib
seaborn
transformers
onnxruntime
apache-tvm
```

I tried everything and I am still getting the following error:
`ModuleNotFoundError: No module named 'transformer_deploy'`

I think this should be installed using `pip install sentence-transformer`, but I am still getting some packages are not installed.

**Comment by VoltaML** [comment]
Hi @hdnh2006. It is easier to pull our docker and work on it. If you try to install it locally, there will be a lot of compatibility issues. Any issues with working with the docker?

**Comment by hdnh2006** [comment]
@VoltaML I am stsill trying, no problems since I started but this repo should be easier to install locally for development purposes, it is not easy to develop inside containers.

Any help would be appreciated, I am open to collaborate with you if necessary.

**Comment by hdnh2006** [comment]
@VoltaML I think there are some issues like a lack of certain files in the repo, but I think I finally could do it.

Your code can be easy integrated into the original yolov5 code. I tried with a private rtsp camera in order to see the improvements of your optimization.

These are my results for yolov5x using just tensorRT:
![image](https://user-images.githubusercontent.com/17271049/202246212-2cb38a5a-4dc8-4c52-8d74-e132746197b1.png)

And these are the results for yolov5x optimized by voltaML:
![image](https://user-images.githubusercontent.com/17271049/202246427-b0364ebf-18ad-417d-bff5-d775daf6a683.png)


In the case of yolov5s, I don't see improvements, maybe the model is too small and I am trying with `bs=1`.

These are my results for yolov5s using just tensorRT:
![image](https://user-images.githubusercontent.com/17271049/202248320-83482314-dfe8-4ed6-bc05-f593649a7585.png)


And these are the results using your optimization:
![image](https://user-images.githubusercontent.com/17271049/202247707-9efbe7a3-b9fe-43ee-b2e4-5473eaa8c819.png)

As I told you, I'll try another batch size and I'll let you know

**Comment by VoltaML** [comment]
> @VoltaML I think there are some issues like a lack of certain files in the repo, but I think I finally could do it.
> 
> Your code can be easy integrated into the original yolov5 code. I tried with a private rtsp camera in order to see the improvements of your optimization.
> 
> These are my results for yolov5x using just tensorRT: ![image](https://user-images.githubusercontent.com/17271049/202246212-2cb38a5a-4dc8-4c52-8d74-e132746197b1.png)
> 
> And these are the results for yolov5x optimized by voltaML: ![image](https://user-images.githubusercontent.com/17271049/202246427-b0364ebf-18ad-417d-bff5-d775daf6a683.png)
> 
> In the case of yolov5s, I don't see improvements, maybe the model is too small and I am trying with `bs=1`.
> 
> These are my results for yolov5s using just tensorRT: ![image](https://user-images.githubusercontent.com/17271049/202248320-83482314-dfe8-4ed6-bc05-f593649a7585.png)
> 
> And these are the results using your optimization: ![image](https://user-images.githubusercontent.com/17271049/202248742-959ac178-6772-4dc5-b015-3678afd6a297.png)
> 
> As I told you, I'll try another batch size and I'll let you know.
> 
> If you need help to improve the documentation, I would love to collaborate.

Hi, @hdnh2006. Great to see that you're benefiting with our repo.  Usually small models may not give that big of a difference. But have you compared the performance of voltaML vs vanilla PyTorch for YoloV5s?

Sure, we'd love to collaborate with you on the documentation part. Please shoot me an email at harish@voltaml.com.
